### ISSUE TITLE
C1orf87 is not shown in the lollipop plot

### ISSUE THREAD

**Issue by aakrosh** [Ahmed-2026/Shiny-App#1]
There is a single nonsense mutation for the gene C1orf87.  While it is identified as a stop codon, it doesn't render correctly, unlike other genes with stop codons.

**Comment by aakrosh** [comment]
g3viz uses a data frame named hgnc2pfam.df to convert the gene symbol (e.g., STAT3, C1ORF87…) to Uniprot IDs which are then used to pull out the protein structure/domain information. This data frame does not have C1ORF87 as an entry. So we have two options:

1. We remove C1ORF87 from the list of genes that are shown in the app.
2. We modify the data frame hgnc2pfam.df  to include this gene and the uniprot id (https://www.uniprot.org/uniprotkb/Q8N0U7/entry).

C1orf87 is an uncharaterized human protein, so I am inclined to recommend option 1 for now. We can revisit this issue later. 

We should add a list of blacklisted genes to the code. Mutations in these genes should be removed from the data frame after reading. For now this blacklist should contain C1orf87, but we will be able to add more genes to it if a similar situation arises.

**Comment by Ahmed-2026** [comment]
The issue with C1orf87 has been resolved by implementing a blacklist feature in the Shiny app. A blacklist vector has been created in the server function:

blacklisted_genes <- c("C1orf87")

This implementation addresses the issue by removing C1orf87 from the list of genes shown in the app, as recommended. The blacklist can be easily expanded to include other genes if similar situations arise in the future. The app now handles the C1orf87 gene appropriately, preventing rendering issues related to its uncharacterized protein structure.
